swipe:
  3:
    left:
      command: 'xdotool key super+Page_Down'
    right:
      command: 'xdotool key super+Page_Up'
    up:
      command: 'xdotool key ctrl+Page_Up'
    down:
      command: 'xdotool key ctrl+Page_Down'
  4:
    left:
      command: 'xdotool key alt+Shift+Tab'
    right:
      command: 'xdotool key alt+Tab'
    up:
      command: 'xdotool key super'
    down:
      command: 'xdotool key super'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
